services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    #volumes:
      # - ./server/src/main/resources/schema_populate.sql:/docker-entrypoint-initdb.d/init.sql
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: no
    ports:
      - 8001:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=./ticketService-realm.json
    command:
      - start-dev
      - --import-realm
#  app:
#    image: gcr.io/ticketserviceapp/ticketservice
#    container_name: ticketService
#    ports:
#      - 8080:8080
#    environment:
#      - DB_HOST=${DB_HOST}


